# -*- coding: utf-8 -*-
"""def_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J3j5yIsk5byZRUfvaDlTcC5G08f0kvCI

**Space Tokenization**
"""

from nltk.tokenize import SpaceTokenizer
tk = SpaceTokenizer()
text = "The Subject contents are very very very much related to NLP subject and MLC subject"
space = tk.tokenize(text)
print(space)
tokens = len(space)
print(tokens)

"""**Case Folding**"""

space_tokens_lc = [word.lower() for word in space]

#see the result
print(space_tokens_lc)

"""**Stop Words Removal**"""

#import the stopwords list
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

#take a look at what stop words are included:
STOP= stopwords.words('english')
print(STOP)

word_tokens_clean=[word for word in space_tokens_lc if word not in STOP]
print(word_tokens_clean)

"""**Type Token Ratio**"""

print(space)

#a=set(space)
#b=list(a)
#c=len(b)
#print(c)
Type_words=list(set(space))
print(Type_words)
Type=len(Type_words)
print(Type)

TTR=(Type/tokens)
print(TTR)