# -*- coding: utf-8 -*-
"""STU_7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zz-gW3gDBkjmvhLvHZ3v-4WG1wqdihVS
"""

import spacy
from spacy import displacy

NER = spacy.load('en_core_web_sm')

raw_text="The Mars Orbiter Mission (MOM), informally known as Mangalyaan, was launched into Earth orbit on 5 November 2013 by the Indian Space Research Organisation (ISRO) and has entered Mars orbit on 24 September 2014. India thus became the first country to enter Mars orbit on its first attempt. It was completed at a record low cost of $74 million."

text1= NER(raw_text)

for word in text1.ents:
  print(word.text,word.label_)

spacy.explain("GPE")

spacy.explain("ORG")

displacy.render(text1,style="ent",jupyter=True)