# -*- coding: utf-8 -*-
"""VWX_8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L2rF1hG5JlKra5riCBpBh7t_fPk6m-Oa
"""

Bhupendra Jogi 696969

import nltk
nltk.download("wordnet")

from nltk.corpus import wordnet
syns=wordnet.synsets('sad')
print(syns)

from nltk.corpus import wordnet
synonyms=[]
antonyms=[]

for syn in wordnet.synsets ("inside"):
  for l in syn.lemmas():
    synonyms.append (l.name())
    if l.antonyms():
      antonyms.append (l.antonyms()[0].name())
      print(set(synonyms))
      print(set(antonyms))

"""POST LAB WORK

Hypernyms and Hyponyms
"""

import nltk
nltk.download("wordnet")

from nltk.corpus import wordnet
syns=wordnet.synsets('Angry')
print(syns)

from nltk.corpus import wordnet
hypernyms=[]
hyponyms=[]

for syn in wordnet.synsets ("book"):
  for l in syn.lemmas():
    hypernyms.append (l.name())
    if l.hyponyms():
      hyponyms.append (l.hyponyms()[0].name())
print(set(hypernyms))
print(set(hyponyms))

"""Meronymy and Holonymy"""

import nltk
nltk.download("wordnet")

from nltk.corpus import wordnet
syns=wordnet.synsets('happy')
print(syns)

from nltk.corpus import wordnet
meronyms=[]
holonyms=[]

for syn in wordnet.synsets("wheel"):
    for lemma in syn.lemmas():
        meronyms.append(lemma.name())


    if syn.part_holonyms():
        for holonym in syn.part_holonyms():
            holonyms.append(holonym.name())


print(set(meronyms))
print(set(holonyms))